### ISSUE TITLE
Cannot read property 'loading' of undefined; [Component] Property Observer Error

### ISSUE THREAD

**Issue by Ianfrancisuk** [mingenesis/miniprogram-redux#2]
Hi
I'm having a problem using your example, I admit I am a novice coder but cant seem to get it to work:

I think the problem is with the line :
topic => ({ loading: topic.loading })

In the block:
const stateSelector = Reselect.createSelector(
  (state, data) => state[data.topicId],
  topic => ({ loading: topic.loading })
);

It appears that the property 'loading' cannot be read.

Hope you can help as I am looking to migrate redux code from a project and would like to use miniprogram-redux.

Thanks

**Comment by mingenesis** [comment]
Thank you @Ianfrancisuk . 
You can change 'topic => ({ loading: topic.loading })' to 'topic => topic' maybe can fix this bug.
